/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type ShutdownBody struct {
	// Whether the proxy should be shutdown as well (default from Hub config)
	Proxy bool `json:"proxy,omitempty"`
	// Whether users' notebook servers should be shutdown as well (default from Hub config)
	Servers bool `json:"servers,omitempty"`
}
