/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type NameActivityBody struct {
	// Timestamp of last-seen activity for this user. Only needed if this is not activity associated with using a given server.
	LastActivity time.Time                 `json:"last_activity,omitempty"`
	Servers      *UsersnameactivityServers `json:"servers,omitempty"`
}
