/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NameUsersBody struct {
	// List of usernames to add to the group
	Users []string `json:"users,omitempty"`
}
