/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

// Activity for a single server.
type UsersnameactivityServersServerName struct {
	// Timestamp of last-seen activity on this server.
	LastActivity time.Time `json:"last_activity"`
}
