/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Oauth2TokenBody struct {
	// The client id
	ClientId string `json:"client_id"`
	// The client secret
	ClientSecret string `json:"client_secret"`
	// The grant type (always 'authorization_code')
	GrantType string `json:"grant_type"`
	// The code provided by the authorization redirect
	Code string `json:"code"`
	// The redirect url
	RedirectUri string `json:"redirect_uri"`
}
