/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2002 struct {
	// The new API token.
	Token string `json:"token,omitempty"`
}
