/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Service struct {
	// The service's name
	Name string `json:"name,omitempty"`
	// Whether the service is an admin
	Admin bool `json:"admin,omitempty"`
	// The names of roles this service has
	Roles []string `json:"roles,omitempty"`
	// The internal url where the service is running
	Url string `json:"url,omitempty"`
	// The proxied URL prefix to the service's url
	Prefix string `json:"prefix,omitempty"`
	// The PID of the service process (if managed)
	Pid float64 `json:"pid,omitempty"`
	// The command used to start the service (if managed)
	Command []string `json:"command,omitempty"`
	// Additional information a deployment can attach to a service. JupyterHub does not use this field.
	Info *interface{} `json:"info,omitempty"`
}
