/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type NameTokensBody struct {
	// lifetime (in seconds) after which the requested token will expire.
	ExpiresIn float64 `json:"expires_in,omitempty"`
	// A note attached to the token for future bookkeeping
	Note string `json:"note,omitempty"`
	// A list of role names from which to derive scopes. This is a shortcut for assigning collections of scopes; Tokens do not retain role assignment. (Changed in 3.0: roles are immediately resolved to scopes instead of stored on roles.)
	Roles []string `json:"roles,omitempty"`
	// A list of scopes that the token should have. (new in JupyterHub 3.0).
	Scopes []string `json:"scopes,omitempty"`
}
