/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2001Spawner struct {
	// The Python class currently active for spawning single-user notebook servers
	Class string `json:"class,omitempty"`
	// The version of the currently active Spawner
	Version string `json:"version,omitempty"`
}
