/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2003 struct {
	// The new API token for the user
	AccessToken string `json:"access_token,omitempty"`
	// Will always be 'Bearer'
	TokenType string `json:"token_type,omitempty"`
}
