/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2001 struct {
	// The version of JupyterHub itself
	Version string `json:"version,omitempty"`
	// The Python version, as returned by sys.version
	Python string `json:"python,omitempty"`
	// The path to sys.executable running JupyterHub
	SysExecutable string                           `json:"sys_executable,omitempty"`
	Authenticator *InlineResponse2001Authenticator `json:"authenticator,omitempty"`
	Spawner       *InlineResponse2001Spawner       `json:"spawner,omitempty"`
}
