/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Group struct {
	// The group's name
	Name string `json:"name,omitempty"`
	// The names of users who are members of this group
	Users []string `json:"users,omitempty"`
	// Group properties (a dictionary).  Unused by JupyterHub itself, but an extension point to store information about groups.  Added in JupyterHub 3.2.
	Properties *interface{} `json:"properties,omitempty"`
	// The names of roles this group has
	Roles []string `json:"roles,omitempty"`
}
