/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type Token struct {
	// The token itself. Only present in responses to requests for a new token.
	Token string `json:"token,omitempty"`
	// The id of the API token. Used for modifying or deleting the token.
	Id string `json:"id,omitempty"`
	// The user that owns a token (undefined if owned by a service)
	User string `json:"user,omitempty"`
	// The service that owns the token (undefined of owned by a user)
	Service string `json:"service,omitempty"`
	// Deprecated in JupyterHub 3, always an empty list. Tokens have 'scopes' starting from JupyterHub 3.
	Roles []string `json:"roles,omitempty"`
	// List of scopes this token has been assigned. New in JupyterHub 3. In JupyterHub 2.x, tokens were assigned 'roles' insead of scopes.
	Scopes []string `json:"scopes,omitempty"`
	// A note about the token, typically describing what it was created for.
	Note string `json:"note,omitempty"`
	// Timestamp when this token was created
	Created time.Time `json:"created,omitempty"`
	// Timestamp when this token expires. Null if there is no expiry.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Timestamp of last-seen activity using this token. Can be null if token has never been used.
	LastActivity time.Time `json:"last_activity,omitempty"`
	// The session id associated with the token, if any. Only used for tokens set during oauth flows.  Added in 2.0.
	SessionId string `json:"session_id,omitempty"`
}
