/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

// Register activity for specific servers by name. The keys of this dict are the names of servers. The default server has an empty name ('').
type UsersnameactivityServers struct {
	ServerName *UsersnameactivityServersServerName `json:"&lt;server name&gt;,omitempty"`
}
