/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type UsersNameBody struct {
	// the new name (optional, if another key is updated i.e. admin)
	Name string `json:"name,omitempty"`
	// update admin (optional, if another key is updated i.e. name)
	Admin bool `json:"admin,omitempty"`
}
