/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

import (
	"time"
)

type User struct {
	// The user's name
	Name string `json:"name,omitempty"`
	// Whether the user is an admin
	Admin bool `json:"admin,omitempty"`
	// The names of roles this user has
	Roles []string `json:"roles,omitempty"`
	// The names of groups where this user is a member
	Groups []string `json:"groups,omitempty"`
	// The user's notebook server's base URL, if running; null if not.
	Server string `json:"server,omitempty"`
	// The currently pending action, if any
	Pending string `json:"pending,omitempty"`
	// Timestamp of last-seen activity from the user
	LastActivity time.Time `json:"last_activity,omitempty"`
	// The servers for this user. By default: only includes _active_ servers. Changed in 3.0: if `?include_stopped_servers` parameter is specified, stopped servers will be included as well.
	Servers []Server `json:"servers,omitempty"`
	// Authentication state of the user. Only available with admin:users:auth_state scope. None otherwise.
	AuthState *interface{} `json:"auth_state,omitempty"`
}
