/*
 * JupyterHub
 *
 * The REST API for JupyterHub
 *
 * API version: 4.0.0b2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type AuthorizationsTokenBody struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}
